"""Public surface of the yaya kernel.

The kernel owns the event bus, the plugin ABI, and the closed public event
catalog. Everything else — adapters, LLM providers, tools, strategies,
memory, skills — is a plugin. See ``docs/dev/plugin-protocol.md`` for the
authoritative contract.
"""

from __future__ import annotations

from yaya.kernel.approval import (
    DEFAULT_APPROVAL_TIMEOUT_S,
    Approval,
    ApprovalCancelledError,
    ApprovalResult,
    ApprovalRuntime,
    ToolRejectedError,
    get_approval_runtime,
    install_approval_runtime,
    uninstall_approval_runtime,
)
from yaya.kernel.bus import DEFAULT_HANDLER_TIMEOUT_S, EventBus, EventHandler, Subscription
from yaya.kernel.compaction import (
    COMPACTION_ANCHOR_KIND,
    CompactionManager,
    LLMSummarizer,
    Summarizer,
    compact_session,
    estimate_text_tokens,
    install_compaction_manager,
    should_auto_compact,
)
from yaya.kernel.config import (
    CONFIG_PATH,
    CompactionConfig,
    KernelConfig,
    SessionConfig,
    default_config_path,
    flatten_kernel_config,
    load_config,
)
from yaya.kernel.config_store import (
    ConfigStore,
    ConfigView,
    default_config_db_path,
)
from yaya.kernel.errors import (
    ConfigError,
    KernelError,
    PluginError,
    YayaError,
    YayaTimeoutError,
)
from yaya.kernel.events import (
    PUBLIC_EVENT_KINDS,
    Event,
    PublicEventKind,
    new_event,
)
from yaya.kernel.llm import (
    APIConnectionError,
    APIEmptyResponseError,
    APIStatusError,
    APITimeoutError,
    ChatProviderError,
    ContentPart,
    LLMProvider,
    RetryableChatProvider,
    StreamedMessage,
    StreamPart,
    ThinkingEffort,
    TokenUsage,
    ToolCallPart,
    anthropic_to_chat_provider_error,
    convert_httpx_error,
    openai_to_chat_provider_error,
)
from yaya.kernel.logging import configure_logging, get_plugin_logger
from yaya.kernel.loop import AgentLoop, LoopConfig
from yaya.kernel.plugin import Category, KernelContext, Plugin
from yaya.kernel.providers import (
    PROVIDERS_PREFIX,
    PROVIDERS_SEEDED_MARKER,
    InstanceRow,
    ProvidersView,
)
from yaya.kernel.registry import PluginRegistry, PluginStatus, validate_install_source
from yaya.kernel.session import (
    MemoryTapeStore,
    Session,
    SessionInfo,
    SessionStore,
    default_session_dir,
    tape_name_for,
)
from yaya.kernel.session_context import (
    DEFAULT_HEARTBEAT_TIMEOUT_S,
    DEFAULT_MAX_CONNECTIONS,
    Connection,
    ConnectionLimitError,
    DetachReason,
    SessionContext,
    SessionManager,
    install_session_manager,
)
from yaya.kernel.session_persister import SessionPersister, install_session_persister
from yaya.kernel.tape_context import (
    after_last_anchor,
    default_tape_context,
    select_messages,
)
from yaya.kernel.tool import (
    DisplayBlock,
    JsonBlock,
    MarkdownBlock,
    TextBlock,
    Tool,
    ToolAlreadyRegisteredError,
    ToolError,
    ToolOk,
    ToolReturnValue,
    dispatch,
    get_tool,
    install_dispatcher,
    mark_legacy_tool,
    register_tool,
    registered_tools,
    unregister_tool,
)

__all__ = [
    "COMPACTION_ANCHOR_KIND",
    "CONFIG_PATH",
    "DEFAULT_APPROVAL_TIMEOUT_S",
    "DEFAULT_HANDLER_TIMEOUT_S",
    "DEFAULT_HEARTBEAT_TIMEOUT_S",
    "DEFAULT_MAX_CONNECTIONS",
    "PROVIDERS_PREFIX",
    "PROVIDERS_SEEDED_MARKER",
    "PUBLIC_EVENT_KINDS",
    "APIConnectionError",
    "APIEmptyResponseError",
    "APIStatusError",
    "APITimeoutError",
    "AgentLoop",
    "Approval",
    "ApprovalCancelledError",
    "ApprovalResult",
    "ApprovalRuntime",
    "Category",
    "ChatProviderError",
    "CompactionConfig",
    "CompactionManager",
    "ConfigError",
    "ConfigStore",
    "ConfigView",
    "Connection",
    "ConnectionLimitError",
    "ContentPart",
    "DetachReason",
    "DisplayBlock",
    "Event",
    "EventBus",
    "EventHandler",
    "InstanceRow",
    "JsonBlock",
    "KernelConfig",
    "KernelContext",
    "KernelError",
    "LLMProvider",
    "LLMSummarizer",
    "LoopConfig",
    "MarkdownBlock",
    "MemoryTapeStore",
    "Plugin",
    "PluginError",
    "PluginRegistry",
    "PluginStatus",
    "ProvidersView",
    "PublicEventKind",
    "RetryableChatProvider",
    "Session",
    "SessionConfig",
    "SessionContext",
    "SessionInfo",
    "SessionManager",
    "SessionPersister",
    "SessionStore",
    "StreamPart",
    "StreamedMessage",
    "Subscription",
    "Summarizer",
    "TextBlock",
    "ThinkingEffort",
    "TokenUsage",
    "Tool",
    "ToolAlreadyRegisteredError",
    "ToolCallPart",
    "ToolError",
    "ToolOk",
    "ToolRejectedError",
    "ToolReturnValue",
    "YayaError",
    "YayaTimeoutError",
    "after_last_anchor",
    "anthropic_to_chat_provider_error",
    "compact_session",
    "configure_logging",
    "convert_httpx_error",
    "default_config_db_path",
    "default_config_path",
    "default_session_dir",
    "default_tape_context",
    "dispatch",
    "estimate_text_tokens",
    "flatten_kernel_config",
    "get_approval_runtime",
    "get_plugin_logger",
    "get_tool",
    "install_approval_runtime",
    "install_compaction_manager",
    "install_dispatcher",
    "install_session_manager",
    "install_session_persister",
    "load_config",
    "mark_legacy_tool",
    "new_event",
    "openai_to_chat_provider_error",
    "register_tool",
    "registered_tools",
    "select_messages",
    "should_auto_compact",
    "tape_name_for",
    "uninstall_approval_runtime",
    "unregister_tool",
    "validate_install_source",
]
